Import("env")

from pathlib import Path

project_dir = Path(env["PROJECT_DIR"])
output_path = project_dir / "src" / "EmbeddedAssets.generated.h"
assets = (
    ("kBinjgbJs", project_dir / "vendor" / "binjgb" / "binjgb.js"),
    ("kPlayerJs", project_dir / "vendor" / "binjgb" / "player.js"),
    ("kBinjgbWasm", project_dir / "vendor" / "binjgb" / "binjgb.wasm"),
    ("kSplashJpg", project_dir / "assets" / "pocketboy_splash.jpg"),
)

lines = [
    "// Generated by scripts/embed_assets.py. Do not edit by hand.",
    "#pragma once",
    "#include <Arduino.h>",
    "",
]

for symbol, asset_path in assets:
    data = asset_path.read_bytes()
    lines.append(f"inline const uint8_t {symbol}[] PROGMEM = {{")
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    lines.append("};")
    lines.append(f"inline constexpr size_t {symbol}Size = sizeof({symbol});")
    lines.append("")

content = "\n".join(lines)
if not output_path.exists() or output_path.read_text() != content:
    output_path.write_text(content)
